nelmio_api_doc:
    documentation:
        info:
            title: API Poker Texas Holdem
            description: Une API de Stéphane... !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
